#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    companyName:
      type: string
      required: true
      example: "travenontip"
    availableSeats:
        type: number
        required: true
        example: 20
    departureDateTime:
      type: string
      required: true
      example: "2019-04-30T16"
    travelRoute:
      type: object
      properties:
        destinationLocation:
          type: object
          properties:
            locationCode:
             type: string
             required: true
             example: "KLG-MY"
            locationDesc:
             type: string
             required: true
             example: "Klang Malaysia"
        originLocation:
          type: object
          properties:
            locationCode:
              type: string
              required: true
              example: "KLG-MY"
            locationDesc:
              type: string
              required: true
              example: "Klang Malaysia"